name: "running test"

on:
  pull_request:
    paths:
      - '**/*.ts'

jobs:
  testing:
    name: "testing"
    runs-on: "ubuntu-latest"
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PGUSER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: "setup node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: setup and running unit test
        run: |
          npm install
          npm run migrate
          # npm run seed
          mkdir public
          npm test
          npm run test:e2e
        env:
          DATABASE_URL: "postgresql://${{ secrets.PGUSER_TEST }}:${{ secrets.PGPASSWORD_TEST }}@localhost:5432/${{ secrets.PGDATABASE_TEST }}?schema=public"
          # token
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY_TEST }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY_TEST }}
          ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE_TEST }}
          REFRESH_TOKEN_AGE: ${{ secrets.REFRESH_TOKEN_AGE_TEST }}
          # super seed
          SUPER_NAME: ${{ secrets.SUPER_NAME_TEST }}
          SUPER_USERNAME: ${{ secrets.SUPER_USERNAME_TEST }}
          SUPER_EMAIL: ${{ secrets.SUPER_EMAIL_TEST }}
          SUPER_PASSWORD: ${{ secrets.SUPER_PASSWORD_TEST }}
